{
 "title": "Deployment",
 "tags": [ "patching" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "name", "label": "Associations", "query": "filewave_associations" },
   { "name": "server", "label": "Server", "query": "${VAR_SERVER}" }
  ]
 },
 "panels": [
  {
   "title": "Server Model Number",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "filewave_model_version{job=\"fwxserver-admin\"}"
    }
   ]
  },
  {
   "title": "Device by Client Version",
   "type": "grafana-piechart-panel",
   "description": "Shows a breakdown of managed devices by FileWave Client version number.",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(extra_metrics_per_device_information) by (fw_client_version)",
     "legendFormat": "{{fw_client_version}}"
    }
   ]
  },
  {
   "title": "Devices By OS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "count(extra_metrics_per_device_information) by (platform)",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Query Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Extra Metrics Query Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(extra_metrics_http_request_time_taken_bucket[5m])) by (le, method))",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Device Checkin / Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "# Devices" }
   ],
   "targets": [
    {
     "expr": "extra_metrics_devices_by_checkin_days{days=\"Less than 1\"}",
     "legendFormat": "Less than 1 day"
    },
    {
     "expr": "extra_metrics_devices_by_checkin_days{days=\"Less than 7\"}",
     "legendFormat": "Less than 7 days"
    },
    {
     "expr": "extra_metrics_devices_by_checkin_days{days=\"Less than 30\"}",
     "legendFormat": "7 - 30 days"
    },
    {
     "expr": "extra_metrics_devices_by_checkin_days{days=\"More than 30\"}",
     "legendFormat": "> 30 days"
    }
   ]
  },
  {
   "title": "Location Tracking",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(extra_metrics_per_device_information{tracked=\"True\"})  "
    }
   ]
  },
  { "title": "Important Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$name",
   "type": "filewave-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "name",
   "targets": [
    {
     "expr": "filewave_associations{association_name=\"${name:raw}\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}