{
 "title": "Patching Status",
 "description": "Shows software patch status summary information",
 "tags": [ "patching" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "${VAR_SERVER}" }
  ]
 },
 "panels": [
  {
   "title": "Patch Progression",
   "type": "grafana-piechart-panel",
   "description": "Shows software patches grouped by state / progress",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state  ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "# Devices by Time",
   "type": "graph",
   "description": "Shows the number of devices over time, grouped by their patch status.  You can use this to track progress over time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Updates by Platform",
   "type": "grafana-piechart-panel",
   "description": "Total proportion of updates by platform.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_platform) by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  { "title": "Updates Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Critical Updates",
   "type": "singlestat",
   "description": "Shows the total number of critical updates that are waiting to be deployed (or are in progress).",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device{is_update_critical=\"True\"})"
    }
   ]
  },
  {
   "title": "Total Other Updates",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device{is_update_critical=\"False\"})"
    }
   ]
  },
  {
   "title": "Devices Affected",
   "type": "singlestat",
   "description": "Shows the number of devices with pending updates (scope of the required updates)",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(extra_metrics_software_updates_by_device)"
    }
   ]
  },
  {
   "title": "Top 10 Non Compliant Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_device) by (device_name, device_id)",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}